import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <div>
            <img id="logo" alt="" src="next.svg" />
            <a href="/">Koti</a>
            <a href="/blog">Blogi</a>
            <a href="/about">Tietoja</a>
          </div>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
